package com.feidao.web.backend.model;

import java.util.Date;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Employee generated by hbm2java
 */
@XmlRootElement
@XmlType(propOrder = {"id", "firstName", "lastName", "telephone", "email", "created"})
@JsonPropertyOrder({"id", "firstName", "lastName", "telephone", "email", "created"})
public class Employee implements java.io.Serializable {

	private static final long serialVersionUID = 5981949404860416484L;
	
	private Integer id;
	private String firstName;
	private String lastName;
	private String telephone;
	private String email;
	private Date created;

	public Employee() {
	}

	public Employee(Date created) {
		this.created = created;
	}

	public Employee(String firstName, String lastName, String telephone,
			String email, Date created) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.telephone = telephone;
		this.email = email;
		this.created = created;
	}
	
	@XmlElement
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@XmlElement
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	@XmlElement
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	@XmlElement
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}
	
	@XmlElement
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	@XmlElement
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}